/* The following code was generated by JFlex 1.4.3 on 24/08/16 11:44 */

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 24/08/16 11:44 from the specification file
 * <tt>analisislexico.flex</tt>
 */
public class analisisLexico {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\30\1\32\25\0\1\30\11\0\1\33\3\0\1\3\1\31"+
    "\12\1\47\0\1\11\1\4\1\13\1\24\1\10\1\21\1\22\1\26"+
    "\1\17\1\2\1\12\1\6\1\2\1\15\1\5\1\2\1\2\1\7"+
    "\1\14\1\16\1\20\1\23\1\25\1\27\2\2\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\12\3\1\4\1\1\2\0\11\3"+
    "\1\5\5\3\2\0\1\6\11\3\1\7\4\3\1\10"+
    "\1\0\1\11\2\3\1\12\3\3\1\13\3\3\1\14"+
    "\1\3\1\15\1\16\3\3\1\17\1\3\1\20\1\21"+
    "\1\22\1\23\1\24\3\3\1\25\1\26";

  private static int [] zzUnpackAction() {
    int [] result = new int[81];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\34\0\70\0\124\0\160\0\214\0\250\0\304"+
    "\0\340\0\374\0\u0118\0\u0134\0\u0150\0\u016c\0\u0188\0\70"+
    "\0\u01a4\0\u01c0\0\u01dc\0\u01f8\0\u0214\0\u0230\0\u024c\0\u0268"+
    "\0\u0284\0\u02a0\0\124\0\u02bc\0\u02d8\0\u02f4\0\u0310\0\u032c"+
    "\0\u0348\0\u0364\0\u01a4\0\u0380\0\u039c\0\u03b8\0\u03d4\0\u03f0"+
    "\0\u040c\0\u0428\0\u0444\0\u0460\0\124\0\u047c\0\u0498\0\u04b4"+
    "\0\u04d0\0\34\0\u04ec\0\124\0\u0508\0\u0524\0\124\0\u0540"+
    "\0\u055c\0\u0578\0\124\0\u0594\0\u05b0\0\u05cc\0\124\0\u05e8"+
    "\0\u0364\0\124\0\u0604\0\u0620\0\u063c\0\124\0\u0658\0\124"+
    "\0\124\0\124\0\124\0\124\0\u0674\0\u0690\0\u06ac\0\124"+
    "\0\124";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[81];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\2\1\5\2\4\1\6\1\7"+
    "\2\4\1\10\2\4\1\11\1\12\1\4\1\13\1\4"+
    "\1\14\1\4\1\15\2\4\1\16\1\17\1\16\1\2"+
    "\35\0\1\20\1\0\1\21\31\0\2\4\1\0\24\4"+
    "\5\0\2\4\1\0\1\4\1\22\1\4\1\23\20\4"+
    "\5\0\2\4\1\0\4\4\1\24\17\4\5\0\2\4"+
    "\1\0\2\4\1\25\20\4\1\26\5\0\2\4\1\0"+
    "\1\4\1\27\1\30\21\4\5\0\2\4\1\0\3\4"+
    "\1\31\20\4\5\0\2\4\1\0\11\4\1\32\3\4"+
    "\1\33\6\4\5\0\2\4\1\0\1\4\1\34\1\35"+
    "\2\4\1\36\16\4\5\0\2\4\1\0\1\4\1\37"+
    "\22\4\5\0\2\4\1\0\22\4\1\40\1\4\34\0"+
    "\1\16\1\0\1\16\32\0\1\41\1\0\1\42\1\0"+
    "\1\43\33\0\2\4\1\0\1\4\1\44\22\4\5\0"+
    "\2\4\1\0\4\4\1\45\17\4\5\0\2\4\1\0"+
    "\12\4\1\46\11\4\5\0\2\4\1\0\10\4\1\47"+
    "\13\4\5\0\2\4\1\0\12\4\1\50\11\4\5\0"+
    "\2\4\1\0\11\4\1\51\12\4\5\0\2\4\1\0"+
    "\5\4\1\52\16\4\5\0\2\4\1\0\14\4\1\53"+
    "\7\4\5\0\2\4\1\0\12\4\1\54\11\4\5\0"+
    "\2\4\1\0\3\4\1\55\20\4\5\0\2\4\1\0"+
    "\1\4\1\56\22\4\5\0\2\4\1\0\2\4\1\57"+
    "\21\4\5\0\2\4\1\0\13\4\1\60\10\4\5\0"+
    "\2\4\1\0\13\4\1\61\10\4\4\0\32\41\1\62"+
    "\1\41\32\42\1\0\1\63\1\0\2\4\1\0\2\4"+
    "\1\64\21\4\5\0\2\4\1\0\5\4\1\65\16\4"+
    "\5\0\2\4\1\0\14\4\1\66\7\4\5\0\2\4"+
    "\1\0\4\4\1\67\17\4\5\0\2\4\1\0\4\4"+
    "\1\70\17\4\5\0\2\4\1\0\12\4\1\71\11\4"+
    "\5\0\2\4\1\0\10\4\1\72\13\4\5\0\2\4"+
    "\1\0\4\4\1\73\17\4\5\0\2\4\1\0\4\4"+
    "\1\74\17\4\5\0\2\4\1\0\5\4\1\75\16\4"+
    "\5\0\2\4\1\0\10\4\1\76\13\4\5\0\2\4"+
    "\1\0\20\4\1\77\3\4\5\0\2\4\1\0\2\4"+
    "\1\100\21\4\4\0\31\42\1\101\1\0\1\63\1\0"+
    "\2\4\1\0\6\4\1\102\15\4\5\0\2\4\1\0"+
    "\3\4\1\103\20\4\5\0\2\4\1\0\3\4\1\104"+
    "\20\4\5\0\2\4\1\0\13\4\1\105\10\4\5\0"+
    "\2\4\1\0\10\4\1\106\13\4\5\0\2\4\1\0"+
    "\16\4\1\107\5\4\5\0\2\4\1\0\12\4\1\110"+
    "\11\4\5\0\2\4\1\0\4\4\1\111\17\4\5\0"+
    "\2\4\1\0\4\4\1\112\17\4\5\0\2\4\1\0"+
    "\11\4\1\113\12\4\5\0\2\4\1\0\11\4\1\114"+
    "\12\4\5\0\2\4\1\0\11\4\1\115\12\4\5\0"+
    "\2\4\1\0\4\4\1\116\17\4\5\0\2\4\1\0"+
    "\14\4\1\117\7\4\5\0\2\4\1\0\3\4\1\120"+
    "\20\4\5\0\2\4\1\0\4\4\1\121\17\4\4\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1736];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\15\1\2\0\17\1\2\0\17\1\1\11"+
    "\1\0\36\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[81];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public analisisLexico(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public analisisLexico(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 76) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { System.out.print(yytext());
          }
        case 23: break;
        case 22: 
          { System.out.println("Se reconoció la palabra reservada continue: " + yytext() );
          }
        case 24: break;
        case 2: 
          { System.out.println("Se reconoció el número: " + yytext() );
          }
        case 25: break;
        case 7: 
          { System.out.println("Se reconoció la palabra reservada for: " + yytext() );
          }
        case 26: break;
        case 18: 
          { System.out.println("Se reconoció la palabra reservada while: " + yytext() );
          }
        case 27: break;
        case 4: 
          { System.out.println("Se reconoció un espacio en blanco: "+ yytext() );
          }
        case 28: break;
        case 16: 
          { System.out.println("Se reconoció la palabra reservada float: " + yytext() );
          }
        case 29: break;
        case 9: 
          { System.out.println("Se reconoció la palabra reservada bool: " + yytext() );
          }
        case 30: break;
        case 10: 
          { System.out.println("Se reconoció la palabra reservada else: " + yytext() );
          }
        case 31: break;
        case 6: 
          { System.out.println("Se reconoció el número real: " + yytext() );
          }
        case 32: break;
        case 14: 
          { System.out.println("Se reconoció la palabra reservada break: " + yytext() );
          }
        case 33: break;
        case 12: 
          { System.out.println("Se reconoció la palabra reservada void: " + yytext() );
          }
        case 34: break;
        case 8: 
          { System.out.println ("Se reconoce un comentario de una linea: "+ yytext() );
          }
        case 35: break;
        case 15: 
          { System.out.println("Se reconoció la palabra reservada class: " + yytext() );
          }
        case 36: break;
        case 5: 
          { System.out.println("Se reconoció la palabra reservada if: " + yytext() );
          }
        case 37: break;
        case 3: 
          { System.out.println("Se reconoció el id: " + yytext() );
          }
        case 38: break;
        case 21: 
          { System.out.println("Se reconoció la palabra reservada integer: " + yytext() );
          }
        case 39: break;
        case 17: 
          { System.out.println("Se reconoció la palabra reservada false: " + yytext() );
          }
        case 40: break;
        case 13: 
          { System.out.println ("Se reconoce un comentario de varias lineas: " + yytext() );
          }
        case 41: break;
        case 11: 
          { System.out.println("Se reconoció la palabra reservada true: " + yytext() );
          }
        case 42: break;
        case 19: 
          { System.out.println("Se reconoció la palabra reservada return: " + yytext() );
          }
        case 43: break;
        case 20: 
          { System.out.println("Se reconoció la palabra reservada extern: " + yytext() );
          }
        case 44: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return YYEOF;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java analisisLexico <inputfile>");
    }
    else {
      for (int i = 0; i < argv.length; i++) {
        analisisLexico scanner = null;
        try {
          scanner = new analisisLexico( new java.io.FileReader(argv[i]) );
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
