
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140611 (SVN rev 31)
// Fri Sep 02 08:15:11 ART 2016
//----------------------------------------------------

package Example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int RES = 18;
  public static final int INTEGER = 41;
  public static final int CONTINUE = 36;
  public static final int FOR = 39;
  public static final int SEMICOLON = 5;
  public static final int AND = 26;
  public static final int IGUAL = 16;
  public static final int OR = 27;
  public static final int BOOL = 33;
  public static final int CLASS = 35;
  public static final int INC = 30;
  public static final int DIV = 22;
  public static final int NUM = 49;
  public static final int EXTERN = 45;
  public static final int IF = 40;
  public static final int ID = 32;
  public static final int MAY_IGUAL = 24;
  public static final int EOF = 0;
  public static final int RETURN = 42;
  public static final int ASIG = 13;
  public static final int SUMASIG = 14;
  public static final int TRUE = 2;
  public static final int error = 1;
  public static final int MUL = 21;
  public static final int MENOR = 19;
  public static final int RESASIG = 15;
  public static final int PAR_C = 7;
  public static final int BREAK = 34;
  public static final int PAR_A = 8;
  public static final int VOID = 43;
  public static final int NO_IGUAL = 28;
  public static final int REAL = 4;
  public static final int MAYOR = 20;
  public static final int GUION_BAJO = 48;
  public static final int COLON = 6;
  public static final int ELSE = 37;
  public static final int PORCENT = 23;
  public static final int PUNTO = 46;
  public static final int MEN_IGUAL = 25;
  public static final int WHILE = 44;
  public static final int FLOAT = 38;
  public static final int NEGAC = 29;
  public static final int SUM = 17;
  public static final int DEC = 31;
  public static final int FALSE = 3;
  public static final int CORCH_C = 12;
  public static final int ALPHA = 47;
  public static final int CORCH_A = 11;
  public static final int MUSTACHE_C = 10;
  public static final int MUSTACHE_A = 9;
}

